"""rename department

Revision ID: 075e91a252c9
Revises: 2f17820df4d2
Create Date: 2025-06-11 23:18:39.395384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075e91a252c9'
down_revision = '2f17820df4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###